### ISSUE TITLE
Database reset documentation should mention username

### ISSUE THREAD

**Issue by Vectornaut** [numberscope/backscope#123] opened 2024-04-17 00:42 UTC
To completely wipe out the database structure, the [documentation](https://github.com/numberscope/backscope/blob/main/doc/resetting-the-database.md#wipe-out-the-whole-database-structure-and-build-a-fresh-database-from-scratch) says to call `dropdb <database name>` and `createdb <database name>`. However, this only works for the user that has access to the database. Other users will need to use the `--username` option:

```bash
dropdb --username=<database user> <database name>
```
```bash
createdb --username=<database user> <database name>
```

**Comment by gwhitney** [comment] 2024-04-17 04:43
Closing as duplicate of #68.

**Closed by gwhitney** 2024-04-17 04:44 UTC
